application: syw-offers
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /static
  static_dir: static

- url: .*
  script: ORS.wsgi.application

libraries:
- name: django
  version: "1.9"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'ORS.settings'
