runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: templates/index.html

- url: /static
  static_dir: static

builtins:
- django_wsgi: on

libraries:

- name: django
  version: "1.9"


env_variables:
  DJANGO_SETTINGS_MODULE: 'ORS.settings'