# YAML Confiuration values
SENDGRID_API_KEY: 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
SENDGRID_SENDER: sywoffers@sendgrid.com
TEMPLATE_ID: c7688a47-1726-4414-82c3-6d12016cde6d
