application: syw-offers
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: demo/index.html
  upload: demo/index.html

- url: /
  static_dir: demo

automatic_scaling:
  min_idle_instances: 1
