# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(default=b'', max_length=64)),
                ('max_per_member_issuance_frequency', models.CharField(default=b'', max_length=128)),
                ('max_value', models.IntegerField(default=100)),
                ('min_value', models.IntegerField(default=0)),
                ('valid_till', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Offers'),
            preserve_default=False,
        ),
    ]
